MyApplication/WebApplication2/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IProductRepository repository;

        public AdminController(IProductRepository repository)
        {
            this.repository = repository;
        }
        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            var product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        public ActionResult Delete(int ProductID)
        {
            var deleteProduct = repository.DeleteProduct(ProductID);
            if (deleteProduct != null)
            {
                TempData["message"] = string.Format("{0} 已删除", deleteProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

MyApplication/WebApplication2/Controllers/ProductController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ProductController : Controller
    {

        IProductRepository repository;
        public int PageSize = 2;
        public ProductController(IProductRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel();
            model.Products = repository.Products.Where(p => category == null || p.Category == category).OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize);
            model.PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = repository.Products.Where(p => category == null || p.Category == category).Count() };
            model.CurrentCategory = category;
            return View(model);
        }

        //异步action,适用于耗时，低cpu活动（非cup密集型）
        public async Task<ActionResult> AsyncList(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel();
            model.Products = await Task<IEnumerable<Product>>.Factory.StartNew(
                () => {
                    Thread.Sleep(2000);//模拟长时间等待，但并不耗费cup，使用异步action释放工作线程，使其在等待期间去响应其他请求
                    return repository.Products.Where(p => category == null || p.Category == category).OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize);
                });         
            model.PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = repository.Products.Where(p => category == null || p.Category == category).Count() };
            model.CurrentCategory = category;
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public PartialViewResult Count()
        {
            return PartialView(repository.Products.Count());
        }

        //
        public HttpStatusCodeResult StatusCode()
        {
            
            return new HttpStatusCodeResult(404, "页面没找到");
            //1.更加便捷的404
            //return HttpNotFound();
            //2.表示未经授权的 HTTP 请求的结果。401
            //return new HttpUnauthorizedResult();
        }
    }
}

MyApplication/WebApplication2/Views/Admin/Edit.cshtml
@model Domain.Entities.Product
@{
    ViewBag.Title = "Admin Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    //若出于一些原因，禁用客户端验证，如下
    //HtmlHelper.ClientValidationEnabled = false;
    //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    //1.模型辅助器
    //@Html.EditorForModel()
    <div class="panel-body">
        @Html.HiddenFor(p => p.ProductID)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "ProductID":
                    break;
                case "ImageData":
                    break;
                case "ImageMimeType":
                    break;
                default:
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                    break;
            }
        }
        <div class="form-group">
            <div style="position:relative">
                <label>Image</label>
                <a class='btn' href='javascript:;'>
                    Choose file...
                    <input type="file" name="Image" size="40" style="position:absolute;z-index:2;top:0;left:0;filter:alpha(opacity=0);opacity:0;background-color:transparent;color:transparent;" onchange='$("#upload-file-info").html($(this).val());' />
                </a>
                <span class="label label-info" id="upload-file-info"></span>
            </div>
            @if (Model.ImageData == null)
            {
                <div class="form-control-static" >No Image</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage","Product",new {Model.ProductID })"/>
            }
        </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })
    </div>
}

MyApplication/WebApplication2/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Product>

@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading ">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @item.ProductID
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new { item.ProductID })
                    </td>
                    <td class="text-right">
                        @item.Price.ToString("c")
                    </td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete","Admin"))
                        {
                            @Html.Hidden("ProductID",item.ProductID)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete"/>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new product", "Create",null,new { @class="btn btn-default"})
    </div>
</div>